H-A-V-A/HAVA-Rune-Shop

README.md

Allen - added name on readme

---

README.md

I <3 this branch.
* [x ] added unit tests (or none needed)
* [ x] written relevant docs (or none needed)
* [x ] referenced any relevant issues (or none exist)
---

added austin to the members

---

README.md

Added Henri to readme

---

client/components/navbar.js
package.json
server/db/models/user.js

user-model and navbar- added link cart

---

server/db/models/product.js

*Added product model
-HencTHETANK

Added Product Model

---

server/db/models/index.js
server/db/models/order.js
server/db/models/orderProduct.js
server/db/models/user.js

order and order product models

---

server/api/index.js
server/api/products.js

set up a products router

---

package-lock.json
server/api/products.js

added api/products/ for all products

---

client/components/guest-home.js
client/components/index.js
client/components/navbar.js
client/components/user-home.js
client/routes.js

added GuestHome

---

script/seed.js

* [ x] added unit tests (or none needed)
* [ x] written relevant docs (or none needed)
* [ x] referenced any relevant issues (or none exist)
---
Have a basic list of users, products, one order, and one order product

basic seed file

---

client/components/cart.js

fixed the empty cart bug

---

client/components/ProductList.js
client/components/navbar.js
client/routes.js

WORKING ON BOTH LOG IN AND LOGGED OUT
---

added products to navbar

---

public/index.html

changed title

---

client/components/ProductList.js
client/routes.js

fixed an issue with single products not showing

---

client/components/cart.js
client/components/cartItem.js
client/store/order.js
server/api/index.js
server/api/orders.js
server/api/users.js

State and DB now update onClick

delete from cart now works

---

client/components/ProductList.js
client/components/SingleProduct.js
client/components/cart.js
client/store/order.js
public/style.css
server/api/users.js

added add to cart functionality with quantity

---

client/components/cart.js
client/components/checkout.js
client/routes.js
client/store/order.js
public/style.css
server/api/orders.js
server/api/users.js

---
You can now checkout and have it clear your cart (doesn't yet affect stock)

Checkout page

---

public/style.css

fixed item list going over width

---

server/api/users.js

removed duplicate delete route

---

client/components/ProductList.js
client/components/cart.js
client/routes.js
client/store/order.js
client/store/user.js
server/api/users.js
server/index.js

---
Can add to guest cart from main page and view a guest cart (delete item, single item page add, and checkout still need to be implemented on guest)

Guest session

---

client/components/SingleProduct.js
server/api/orders.js
server/api/products.js

update stock on checkout

---

server/api/auth.js
server/api/users.js

added isAuth

---

server/api/users.js

added authorization on user's delete and place order

---

client/store/order.js
server/api/guest.js

guest delete complete

---

client/components/checkout.js
client/routes.js

Guest session3

---

client/store/order.js
client/store/product.js

---
I tested all the thunks and they still work

added try catches to thunks

---

client/store/order.js
client/store/user.js
server/api/guest.js
server/api/users.js
server/auth/index.js

fixed the bug that was making add to user cart not work

---

client/components/cart.js
client/components/cart.spec.js
client/components/user-home.spec.js
package-lock.json
package.json
public/style.css

Cart component test specs

---

server/db/models/orderProduct.spec.js

added some validations tests to OrderProducts

---

server/api/users.spec.js
server/db/models/user.js

test not working

---

client/components/user-home.spec.js
client/store/user.spec.js
server/api/guest.spec.js
server/api/users.spec.js

added tests for guest add and update

---

server/api/guest.js

guest cart empties after checkout

---

server/api/users.js

fixed stock change on checkout

---

client/components/ProductList.js
client/components/SingleProduct.js
client/components/cart.js
client/components/cartItem.js
client/components/navbar.js
client/store/order.js
server/api/users.js
server/auth/index.js

User sessions

---

client/components/orderHistory.js
client/routes.js
client/store/order.js
server/api/users.js

order history route/thunk/component

---

server/api/users.js

validator? never met her!

---

client/components/not-found.js
client/components/unauthorized.js

fixed images

---

client/components/StripeComponent.js
client/components/checkout.js
client/routes.js
constants/server.js
constants/stripe.js
package-lock.json
package.json
public/style.css

stripe front end

---

client/components/checkout.js
public/style.css
server/db/models/user.js

minor fixes

---

constants/stripe.js

fixed API key
